use Mambos;

INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mambo\'s Platter','Fried Pork Bites, Dominican Style Fried Chicken & Tostones','Regular $14.99 - Large $24.99','appetizer', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Empanadas','Caribbean Style Turnovers Made with Ground Beef, Shredded Chicken, Cheese or Cheese with Guava','2 for $4.99 - 1 for $2.99','appetizer', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Quipes','A Dominican version of the Lebanese kibbeh, made with Whole Grain, Ground Beef, Raisins, Onion, Pepper, Basil & Tomatoes. ','$2.99 each','appetizer', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Yucca Frita','Deep Fried for a Golden-Brown Outer Crisp & Served with Mambo\'s Sauce','S6.99','appetizer', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Ensalada de la Casa','Cabbage, Lettuce, Tomatoes, Cucumbers & Avocado \n + Add Chicken $4.00','$5.99','salad', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mambo\'s Caesar Salad','Caesar Salad Served with Plantain Chips & Avocado Slices \n + Add Chicken $4.00','$7.99','salad', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Martes - Sabado / Tuesday - Saturday','Sopa de Pollo / Chicken Soup or Sopa de Res / Beef Soup','Regular $4.99 - Large $7.99','soup', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Domingo / Sunday','Sancocho / Dominican Specialty Stew Made with a Variety of Meat & Vegetables \n + with White Rice','Regular $7.99 - Large $11.99','soup', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Bistec Encebollado ','Thinly Sliced Seasoned Steak cooked with Onions ','$14.99','beef', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Bistec Guisado / Braised Steak ','Made with our Savory Dominican Seasoning','$13.99','beef', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Bistec Salteado ','Sliced Steak Cooked with Red & Green Peppers ','$14.99','beef', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Pechuga a la Plancha / Grilled Chicken Breast ','Made with our very own Home Made Recipe ','$13.99','chicken', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Pollo Guisado / Braised Chicken ','Served with White Rice and Beans or Moro Rice(of the day) or Vegetables and a small side Salad ','$12.99','chicken', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Chicharrones de Pollo / Fried Chicken ','Dominican Style Fried Chicken made with our special seasoning ','$13.99','chicken', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Chuleta al Salten ','Pan Grilled Pork Chops Flavored with our Dominican Seasoning ','$14.99','pork', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Masita de Cerdo','Fried Pork Bites ','$13.99','pork', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Salmon al Salten ','House Seasoned Grilled Salmon ','$14.99','seafood', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Tilapia en Salsa ','Tilapia Cooked in Tomato Sauce Flavored with Sautéed Onions & Peppers ','$13.99','seafood', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Tilapia Empanizada ','Seasoned and Breaded Tilapia','$13.99','seafood', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Camarones al Ajillo ','Shrimp Made in a Savory Garlic Sauce ','$16.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Camarones en Salsa ','Shrimp in Tomato Sauce Flavored with Sautéed Onions & Peppers ','$16.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mofongo de Chicharrones de Pollo ','Dominican Style Fried Chicken Served with Mofongo and Garlic Sauce','$14.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mofongo de Cerdo ','Pork Bites Served with Mofongo and Garlic Sauce ','$14.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mofongo de Camarones ','Garlic Shrimp Served with Mofongo and Garlic Sauce','$16.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Mangu Tres Golpes ','Mashed Plantains Served with Dominican Salami, Fried Cheese, & Two Fried Eggs ','$13.99','specials', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Chimi-Burger','A Dominican Classic, Seasoned Patty Served with Grilled Onions, Cabbage & "Chimi-Sauce" ','$10.99','sandwich', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Cubano/Cuban Sandwich ','Includes Roast Pork, Ham,Swiss Cheese, Pickles & Mustard ','$11.99','sandwich', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Bistec Sandwich/Steak Sandwich ','Thin Sliced Steak with Peppers & Onions and Swiss Cheese ','$10.99','sandwich', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Pollo/Chicken Sandwich ','Seasoned Grilled Chicken ','$9.99','sandwich', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Maduros/Sweet Plantains ','','$2.99','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Tostones/Fried Green Plantains ','','$2.99','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Arroz/Rice','','M $2.99 - L $4.99','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Habichuelas/Beans','','$1.99','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Papas Fritas/Fries','','$2.49','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Vegetales/Vegetables','','$2.99','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Aguacate/Avocado','','$2.49','side', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Soft Drinks','Coke - Diet Coke - Sprite - Dr. Pepper - Fuze Raspberry Tea -Fuze Unsweetened Tea - Fanta Orange - Powerade Mountain Blast ','$1.99','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Hot Coffee','','$1.99','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Hot Tea','*Green Tea(100% Natural Premiun Green Tea), *Lemon (Flavored Herbal tea with other Natural Flavor), *Mint (Herbal Tea with other Natural Flavors) ','$1.99','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Agua De Coco/Coconut Water ','','$2.49','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Malta/Malt Beverage ','','$2.49','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Country Club Soda','Frambuesa or Merengue','$2.49','drink', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Morir Soñando ','Fresh Orange Juice,Milk and a splash of Vanilla ','$4.99','juice', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Guineo/ Banana - Piña/ Pineapple- Chinola/ Passion Fruit ','','$4.99','juice', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Sapote- Mango- Lechosa/ Papaya -Zanahoria/ Carrot ','','$4.99','juice', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Naranja/ Orange- Limon-Lime ','','$2.50','juice', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Chicken Tenders ','','$4.99','kids', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Cheeseburger','','$4.99','kids', CURDATE(), CURDATE());
INSERT INTO dishes (name,description,price,category,createdAt,updatedAt) VALUES ('Jamon y Queso / Ham and Cheese Sandwich','','$5.99','kids', CURDATE(), CURDATE());